name: Access PC

on:

  push:

    branches: [ main ]

jobs:

  access-pc:

    runs-on: windows-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Access PC

        run: |
        ssh user@85.140.118.123
